//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int MenuID { get; set; }
        public string Title { get; set; }
        public string Action { get; set; }
        public string URL { get; set; }
        public int Position { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
